package org.firstinspires.ftc.teamcode.opmodes;

// WE ARE USING THE FRONT RIGHT OF THE BOT AS THE REFERENCE POINT FOR PINPOINT
//X OFFSET IS FROM THE FORWARD RUNNING POD 20MM (POSITIVE)
//Y OFFSET IS FROM THE STRAFE POD: -241.3MM (NEGATIVE)
// X ENCODER IS FLIPPED, Y IS THE CORRECT DIRECTION

public class IncredibotsAuto {
}
